# Generated by Django 6.0.1 on 2026-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_url',
            field=models.CharField(max_length=500),
        ),
    ]
