# Generated by Django 6.0.1 on 2026-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_application_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
